[package]
name = "ha-backup-uploader"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
rust-s3 = "0.35.1"
serde_json = "1.0.134"
tar = "0.4.43"
tokio = { version = "1.42.0", features = ["rt", "rt-multi-thread", "macros"] }